# Site wide configuration

title:            Ilabharatham
locale:           en_US
#url:              http://ilabharatham.github.io
url: http://127.0.0.1:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Ilabharatham
  avatar: my-self.jpg
  bio: "Helping Hands Are Holier Than Praying Minds"
  email: vishnu667@gmail.com
  facebook: ilabharatham
  google:
    plus: vishnu667
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: ilabharatham

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
